Static Qt build: single-file exe via qtbase-static + QTPLUGIN

diff --git a/.github/workflows/windows-release.yaml b/.github/workflows/windows-release.yaml
--- a/.github/workflows/windows-release.yaml
+++ b/.github/workflows/windows-release.yaml
@@ -15,6 +15,8 @@ defaults:
 env:
   PROG:         cubiomes-viewer
   SOURCE_DIR:   ${{github.workspace}}
+  QTBASE_URL:   https://download.qt.io/archive/qt/5.15/5.15.2/submodules/qtbase-everywhere-src-5.15.2.zip
+  QTPREFIX:     C:\Qt\static\5.15.2\mingw81_64
 
 
 jobs:
@@ -27,7 +29,7 @@ jobs:
         with:
           submodules: recursive
 
-      - name: Install Qt
+      - name: Install Qt (MinGW toolchain + lrelease)
         uses: jurplel/install-qt-action@v3
         with:
           aqtversion:   '==3.1.*'
@@ -39,6 +41,25 @@ jobs:
           cache:        true
           setup-python: false
 
+      - name: Cache static Qt
+        id: cache-qt-static
+        uses: actions/cache@v4
+        with:
+          path: C:\Qt\static\5.15.2\mingw81_64
+          key: qt-static-5.15.2-mingw81-v1
+
+      - name: Build static Qt
+        if: steps.cache-qt-static.outputs.cache-hit != 'true'
+        working-directory: ${{runner.temp}}
+        run:  |
+              perl -v >nul 2>&1 || echo "WARNING: perl not found"
+              curl -L --retry 3 -o qtbase.zip %QTBASE_URL%
+              powershell -Command "Expand-Archive -Force qtbase.zip ."
+              cd qtbase-everywhere-src-5.15.2
+              configure.bat -opensource -confirm-license -release -static -platform win32-g++ -prefix %QTPREFIX% -nomake examples -nomake tests -no-opengl -no-angle -no-icu -no-openssl -no-dbus -no-vulkan -no-egl -qt-zlib -qt-libpng -qt-libjpeg -qt-freetype -qt-pcre -qt-harfbuzz
+              mingw32-make -j2
+              mingw32-make install
+
       - name: Regenerate translations
         working-directory: ${{env.SOURCE_DIR}}
         run:  |
@@ -47,21 +68,21 @@ jobs:
       - name: Build
         working-directory: ${{env.SOURCE_DIR}}
         run:  |
-              qmake CONFIG+=release ${{env.SOURCE_DIR}}
-              mingw32-make
-              
-      - name: Deploy
+              "%QTPREFIX%\bin\qmake.exe" CONFIG+=release %SOURCE_DIR%
+              "%QTPREFIX%\bin\mingw32-make.exe"
+
+      - name: Package
         working-directory: ${{env.SOURCE_DIR}}
         run:  |
-              mkdir ${{env.PROG}}
-              copy ${{env.SOURCE_DIR}}\release\${{env.PROG}}.exe ${{env.PROG}}
-              windeployqt --dir ${{env.PROG}} ${{env.SOURCE_DIR}}\release\${{env.PROG}}.exe --compiler-runtime --no-translations --no-system-d3d-compiler --no-opengl-sw --no-angle
-              ${{env.SOURCE_DIR}}\${{env.PROG}}\${{env.PROG}}.exe --version
+              mkdir %PROG%
+              copy release\%PROG%.exe %PROG%\
+              echo --- DLL imports ---
+              objdump -p %PROG%\%PROG%.exe | findstr /i "DLL Name"
+              echo --- version ---
+              %PROG%\%PROG%.exe --version
 
       - name: Save build artifact
         uses: actions/upload-artifact@v4
         with:
           name: ${{env.PROG}}-win
           path: ${{env.SOURCE_DIR}}\${{env.PROG}}
-
-
